export const ITEM = {
  START: 'ITEM.START',
  FAILED: 'ITEM.FAILED',
  GET: 'ITEM.GET',
  POST: 'ITEM.POST',
  START_POST: 'ITEM.START_POST',
  FAILED_POST: 'ITEM.FAILED_POST',
  SUCCESS_POST: 'ITEM.SUCCESS_POST',
};

export const LOGIN = {
  START: 'LOGIN.START',
  REGISTER: 'LOGIN.REGISTER',
  START_REGISTER: 'LOGIN.START_REGISTER',
  LOGIN: 'LOGIN.LOGIN',
  FAILED: 'LOGIN.FAILED',
  LOGOUT: 'LOGIN.LOGOUT',
};
